aptamer_info_set = {...
    'rot_broc','GUCGAGUAGAGUGUGGNNNNNNNNNNNNNNNNNNNNCGGUCGGGUCC','(..((.(.((...(.(((((((((....))))))))).))).).)))';...
    % 'std_broc','CGGUCGGGUCCNNNNNNNNNNNNNNNNNNNNGUCGAGUAGAGUGUGG','(.(((.(.(((((((((((....)))))))))..)).).))...).)';...
    % 'std_corn','CGAGGAAGGAGGUCUGAGGAGGUCACUG','(.....((..(..((....))..).)))';...
    % 'std_orange_broc','CGGUCGGGUCCNNNNNNNNNNNNNNNNNNNNGUUGAGUAGCGUGUGG','(.(.((.((.(((((((((....))))))))).......)).))).)';...
    % 'rot_orange_broc','GUUGAGUAGCGUGUGGNNNNNNNNNNNNNNNNNNNNCGGUCGGGUCC','(.......((.((..(((((((((....)))))))))...)).)).)';...
    'std_red_broc','CGGUCGGGUCCNNNNNNNNNNNNNNNNNNNNGUUGAGUAGUGUGUGG','(.(...(.(((((((((((....)))))))))..)).)......).)';...
    % 'rot_red_broc','GUUGAGUAGUGUGUGGNNNNNNNNNNNNNNNNNNNNCGGUCGGGUCC','(..((.(......(.(((((((((....))))))))).)...).)))';...
    % 'mangoIII','GGAAGGUUUGGUAUGUGGUAUA','...(.((.....)).)......';...
    % 'mangoIV','CGAGGGAGUGGUGAGGAUGAGGCGA','((.....((.......))....)).';...
    };
